"""Word Chef authoritative game engine.

Every state transition is a pure function:

    (state, intent, clock) -> (new_state, outcome)

The backend owns the state and calls these functions; clients only send
intents. All randomness is derived from the match seed with named streams,
so a finished match can be regenerated byte-exactly from (seed, intents).
"""
from __future__ import annotations

import time
from dataclasses import dataclass, field, replace

from .chaos import ChaosEvent, pick_chaos
from .dictionary import Dictionary, load_dictionary
from .kitchens import KITCHEN_BY_ID, Kitchen, kitchen_for_xp
from .letters import swap_one_letter
from .orders import Order, check_order, make_order
from .rng import Rng, derive_seed
from .scoring import (PREP_TOKEN_CAP, DishResult, prep_score, score_dish)

DEFAULT_ROUNDS = 5
ROUND_DISHES = 3          # successful dishes per player to close a round
GOLDEN_PATIENCE_COST = 1      # +15s on the current order
GOLDEN_RESTOCK_COST = 3      # swap one ingredient
GOLDEN_BOOST_COST = 2        # x1.5 on the next dish
PATIENCE_SECONDS = 15
BOOST_MULT = 1.5


# ───────────────────────────── state ─────────────────────────────

@dataclass
class PlayerState:
    player_id: str
    display_name: str = ""
    score: int = 0
    combo: int = 0
    heat: int = 0
    spice_charges: int = 1
    spice_active: bool = False
    golden: int = 0
    prep_tokens: int = 0
    boost_armed: bool = False
    order: Order | None = None
    order_started_at: float = 0.0
    order_deadline: float = 0.0
    streak_left: int = 0
    double_order: bool = False
    spice_storm: bool = False
    tray_override: str = ""
    used_words: tuple[str, ...] = ()
    dish_count: int = 0
    round_dishes: int = 0
    best_word: str = ""
    best_word_len: int = 0

    def to_dict(self) -> dict:
        return {
            "player_id": self.player_id,
            "display_name": self.display_name,
            "score": self.score, "combo": self.combo, "heat": self.heat,
            "spice_charges": self.spice_charges, "spice_active": self.spice_active,
            "golden": self.golden, "prep_tokens": self.prep_tokens,
            "boost_armed": self.boost_armed,
            "order": self.order.to_dict() if self.order else None,
            "order_started_at": self.order_started_at,
            "order_deadline": self.order_deadline,
            "streak_left": self.streak_left,
            "double_order": self.double_order, "spice_storm": self.spice_storm,
            "tray_override": self.tray_override,
            "used_words": list(self.used_words),
            "dish_count": self.dish_count, "round_dishes": self.round_dishes,
            "best_word": self.best_word, "best_word_len": self.best_word_len,
        }

    @staticmethod
    def from_dict(data: dict) -> "PlayerState":
        data = dict(data)
        order = data.pop("order", None)
        data["order"] = Order.from_dict(order) if order else None
        data["used_words"] = tuple(data.get("used_words") or ())
        return PlayerState(**data)


@dataclass
class MatchState:
    match_id: str
    mode: str                    # SOLO | QUICK_COOK | CHAOS_KITCHEN
    seed: str
    host_player_id: str = ""
    kitchen_id: str = "street"
    rounds_total: int = DEFAULT_ROUNDS
    round_no: int = 0
    round_active: bool = False
    players: dict[str, PlayerState] = field(default_factory=dict)
    created_at: float = 0.0
    finished: bool = False
    chaos_log: list[dict] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "match_id": self.match_id, "mode": self.mode, "seed": self.seed,
            "host_player_id": self.host_player_id,
            "kitchen_id": self.kitchen_id, "rounds_total": self.rounds_total,
            "round_no": self.round_no, "round_active": self.round_active,
            "players": {pid: p.to_dict() for pid, p in self.players.items()},
            "created_at": self.created_at, "finished": self.finished,
            "chaos_log": list(self.chaos_log),
        }

    @staticmethod
    def from_dict(data: dict) -> "MatchState":
        data = dict(data)
        data["players"] = {pid: PlayerState.from_dict(p)
                           for pid, p in data.get("players", {}).items()}
        if not data.get("host_player_id") and data.get("players"):
            data["host_player_id"] = sorted(data["players"])[0]
        return MatchState(**data)


@dataclass(frozen=True)
class Outcome:
    """Result of one intent — the backend records and broadcasts it."""
    accepted: bool
    action: str
    reason: str
    player_id: str = ""
    payload: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {"accepted": self.accepted, "action": self.action,
                "reason": self.reason, "player_id": self.player_id,
                "payload": self.payload}


# ───────────────────────────── lifecycle ─────────────────────────────

def start_match(*, match_id: str, mode: str, seed: str, player_ids: list[str],
                kitchen_id: str = "street", rounds_total: int = DEFAULT_ROUNDS,
                now: float | None = None, display_names: dict | None = None) -> MatchState:
    if mode not in ("SOLO", "QUICK_COOK", "CHAOS_KITCHEN"):
        raise ValueError(f"unknown mode {mode}")
    if not player_ids:
        raise ValueError("a match needs at least one player")
    now = time.time() if now is None else now
    players = {
        pid: PlayerState(player_id=pid,
                         display_name=(display_names or {}).get(pid, pid))
        for pid in player_ids
    }
    return MatchState(
        match_id=match_id, mode=mode, seed=seed, host_player_id=player_ids[0], kitchen_id=kitchen_id,
        rounds_total=rounds_total, players=players, created_at=now,
    )


def _stream(state: MatchState, context: str) -> Rng:
    return Rng(derive_seed(state.seed, f"{state.match_id}:{context}"))


def _kitchen(state: MatchState) -> Kitchen:
    return KITCHEN_BY_ID.get(state.kitchen_id, KITCHEN_BY_ID["street"])


def _difficulty_for(player: PlayerState, base: int, kitchen: Kitchen) -> int:
    """Adaptive difficulty: heat raises the bar, skill keeps it fair."""
    difficulty = base + player.heat // 3 + min(2, player.dish_count // 8)
    return max(1, min(9, difficulty))


def start_round(state: MatchState, *, now: float | None = None) -> MatchState:
    """Open the next round: deal trays and orders to every player."""
    if state.finished:
        raise ValueError("match already finished")
    if state.round_active:
        raise ValueError("round already active")
    now = time.time() if now is None else now
    state = replace(state, round_no=state.round_no + 1, round_active=True)
    kitchen = _kitchen(state)
    base_difficulty = 1 + (state.round_no - 1) // 2 + (0 if state.mode != "CHAOS_KITCHEN" else 1)

    for index, player in enumerate(sorted(state.players.values(), key=lambda p: p.player_id)):
        # QUICK_COOK: one shared order — everyone cooks the same ticket.
        shared = state.mode == "QUICK_COOK"
        context = (f"order:{state.round_no}:shared" if shared
                   else f"order:{state.round_no}:{player.player_id}:{index}")
        rng = _stream(state, context)
        difficulty = _difficulty_for(player, base_difficulty, kitchen)
        theme = kitchen.theme if rng.chance(1, 2) else ""
        order = make_order(
            rng, load_dictionary(),
            order_id=(f"{state.match_id}-r{state.round_no}-shared" if shared
                      else f"{state.match_id}-r{state.round_no}-{player.player_id}"),
            difficulty=difficulty, profile=kitchen.letter_profile,
            theme=theme, force_kind="THEME" if theme and rng.chance(1, 3) else "",
        )
        if player.tray_override:
            order = replace(order, tray=player.tray_override)
            player.tray_override = ""
        deadline = now + order.time_limit * kitchen.timer_mult
        player.order = order
        player.order_started_at = now
        player.order_deadline = deadline
        player.streak_left = order.streak_needed
        player.used_words = ()
        player.round_dishes = 0

    # Chaos Kitchen: a deterministic chaos event opens every round after the first.
    if state.mode == "CHAOS_KITCHEN" and state.round_no > 1:
        rng = _stream(state, f"chaos:{state.round_no}")
        player_ids = sorted(state.players)
        event = pick_chaos(rng, player_ids)
        state = apply_chaos(state, event, now=now)

    return state


def apply_chaos(state: MatchState, event: ChaosEvent, *, now: float | None = None) -> MatchState:
    now = time.time() if now is None else now
    state = replace(state, chaos_log=state.chaos_log + [event.to_dict()])
    victim = state.players.get(event.victim_id)
    actor = state.players.get(event.actor_id)
    if victim is None:
        return state
    if event.event_type == "STEAL_INGREDIENT":
        count = int(event.param or "1")
        if victim.order:
            letters = list(victim.order.tray)
            stolen = []
            for _ in range(min(count, max(0, len(letters) - 4))):
                stolen.append(letters.pop(len(letters) // 2))
            victim.order = replace(victim.order, tray="".join(letters))
            if actor is not None:
                actor.golden += len(stolen)
    elif event.event_type == "BURN_TIMER":
        burn = int(event.param or "8")
        victim.order_deadline = max(now + 2, victim.order_deadline - burn)
    elif event.event_type == "SPICE_STORM":
        for player in state.players.values():
            player.spice_storm = True
    elif event.event_type == "INGREDIENT_SWAP":
        ids = sorted(state.players)
        if len(ids) >= 2:
            other_id = ids[(ids.index(event.victim_id) + 1) % len(ids)]
            other = state.players[other_id]
            if victim.order and other.order:
                victim.order = replace(victim.order, tray=other.order.tray)
                other.order = replace(other.order, tray=victim.order.tray)
    elif event.event_type == "DOUBLE_ORDER":
        victim.double_order = True
    return state


def end_round(state: MatchState, *, now: float | None = None) -> MatchState:
    if not state.round_active:
        raise ValueError("no active round")
    now = time.time() if now is None else now
    for player in state.players.values():
        # Unfinished orders cool the kitchen down.
        if player.order is not None and player.streak_left < player.order.streak_needed:
            pass
        player.order = None
        player.spice_active = False
    finished = state.round_no >= state.rounds_total
    return replace(state, round_active=False, finished=finished)


# ───────────────────────────── intents ─────────────────────────────

def submit_dish(state: MatchState, player_id: str, word: str, *,
                use_spice: bool = False, now: float | None = None) -> tuple[MatchState, Outcome]:
    """The hot path: serve a dish for the player's current order."""
    now = time.time() if now is None else now
    player = state.players.get(player_id)
    if player is None:
        return state, Outcome(False, "SUBMIT_DISH", "unknown_player", player_id)
    if not state.round_active or player.order is None:
        return state, Outcome(False, "SUBMIT_DISH", "no_active_order", player_id)

    order = player.order
    kitchen = _kitchen(state)
    spice_active = use_spice and player.spice_charges > 0
    if player.spice_storm:
        spice_active = True
        player.spice_storm = False

    elapsed = int(max(0.0, now - player.order_started_at))
    timed_out = now > player.order_deadline

    result: DishResult = score_dish(
        word=word, order=order,
        combo_before=player.combo, heat_before=player.heat,
        spice_active=spice_active, prep_tokens=player.prep_tokens,
        kitchen_mult=kitchen.score_mult, elapsed_seconds=elapsed,
        kitchen_rule=kitchen.rule,
    )

    if timed_out and result.valid:
        result = replace(result, valid=False, reason="order_expired",
                         score_delta=0, combo_after=0)

    if use_spice and player.spice_charges > 0 and spice_active:
        player.spice_charges -= 1

    payload: dict = {"dish": result.to_dict(), "order_id": order.order_id,
                     "elapsed_seconds": elapsed, "timed_out": timed_out}

    if not result.valid:
        if spice_active:
            player.prep_tokens = 0
        player.combo = result.combo_after
        player.heat = result.heat_after
        player.spice_active = False
        player.used_words = player.used_words + (word.lower(),)
        if timed_out:
            # the ticket expired — the kitchen sends a fresh one
            rng = _stream(state, f"expired:{player_id}:{player.dish_count}:{state.round_no}")
            fresh = make_order(
                rng, load_dictionary(),
                order_id=f"{order.order_id}#expired{player.dish_count}",
                difficulty=_difficulty_for(player, order.difficulty, kitchen),
                profile=kitchen.letter_profile,
            )
            player.order = fresh
            player.order_started_at = now
            player.order_deadline = now + fresh.time_limit * kitchen.timer_mult
            player.streak_left = fresh.streak_needed
            payload["next_order"] = fresh.to_dict()
        return state, Outcome(True, "SUBMIT_DISH", result.reason, player_id, payload)

    score_delta = result.score_delta
    if player.boost_armed:
        score_delta = int(round(score_delta * BOOST_MULT))
        player.boost_armed = False
        payload["boost_applied"] = True
    if player.double_order:
        score_delta *= 2
        player.double_order = False
        payload["double_order_applied"] = True

    player.score += score_delta
    player.combo = result.combo_after
    player.heat = result.heat_after
    player.golden += result.golden_delta
    player.prep_tokens = 0
    player.used_words = player.used_words + (word.lower(),)
    player.dish_count += 1
    player.round_dishes += 1
    if len(word) > player.best_word_len:
        player.best_word, player.best_word_len = word.lower(), len(word)

    # combo builds spice charges
    if player.combo > 0 and player.combo % 3 == 0 and player.spice_charges < 3:
        player.spice_charges += 1

    payload["score_delta"] = score_delta

    # STREAK orders: keep the same order window until the streak is served.
    if order.kind == "STREAK":
        player.streak_left -= 1
        if player.streak_left > 0:
            player.order = replace(order, used_words=player.used_words)
            payload["streak_left"] = player.streak_left
            return state, Outcome(True, "SUBMIT_DISH", "streak_progress", player_id, payload)

    # Order served: deal the next ticket immediately (round stays hot).
    # QUICK_COOK keeps the ticket stream shared across all chefs.
    shared = state.mode == "QUICK_COOK"
    stream_key = (
        f"next:shared:{player.dish_count}:{state.round_no}"
        if shared else f"next:{player_id}:{player.dish_count}:{state.round_no}"
    )
    rng = _stream(state, stream_key)
    difficulty = _difficulty_for(player, order.difficulty, kitchen)
    next_order = make_order(
        rng, load_dictionary(),
        order_id=(
            f"{order.order_id}#next{player.dish_count}"
            if not shared else f"{state.match_id}-r{state.round_no}-shared#next{player.dish_count}"
        ),
        difficulty=difficulty, profile=kitchen.letter_profile,
    )
    if player.tray_override:
        next_order = replace(next_order, tray=player.tray_override)
        player.tray_override = ""
    player.order = next_order
    player.order_started_at = now
    player.order_deadline = now + next_order.time_limit * kitchen.timer_mult
    player.streak_left = next_order.streak_needed
    payload["next_order"] = next_order.to_dict()
    return state, Outcome(True, "SUBMIT_DISH", "dish_served", player_id, payload)


def submit_prep(state: MatchState, player_id: str, word: str, *,
                now: float | None = None) -> tuple[MatchState, Outcome]:
    """Mise en place: a tiny prep word banks points WITHOUT breaking combo."""
    now = time.time() if now is None else now
    player = state.players.get(player_id)
    if player is None:
        return state, Outcome(False, "PREP", "unknown_player", player_id)
    if not state.round_active or player.order is None:
        return state, Outcome(False, "PREP", "no_active_order", player_id)
    word = (word or "").lower()
    dictionary = load_dictionary()
    if not dictionary.formable(word, player.order.tray):
        return state, Outcome(False, "PREP", "not_formable", player_id)
    if len(word) < 2 or len(word) > 3:
        return state, Outcome(False, "PREP", "prep_needs_2_or_3_letters", player_id)
    if word in player.used_words:
        return state, Outcome(False, "PREP", "word_already_served", player_id)
    if word in dictionary.anagrams(player.order.tray) and len(word) == len(player.order.tray):
        return state, Outcome(False, "PREP", "too_big_for_prep", player_id)

    points = prep_score(word)
    player.score += points
    player.prep_tokens = min(PREP_TOKEN_CAP, player.prep_tokens + 1)
    player.used_words = player.used_words + (word,)
    payload = {"word": word, "points": points, "prep_tokens": player.prep_tokens}
    return state, Outcome(True, "PREP", "prepped", player_id, payload)


def use_golden(state: MatchState, player_id: str, effect: str, *,
               now: float | None = None) -> tuple[MatchState, Outcome]:
    now = time.time() if now is None else now
    player = state.players.get(player_id)
    if player is None:
        return state, Outcome(False, "GOLDEN", "unknown_player", player_id)
    if not state.round_active or player.order is None:
        return state, Outcome(False, "GOLDEN", "no_active_order", player_id)

    if effect == "patience":
        if player.golden < GOLDEN_PATIENCE_COST:
            return state, Outcome(False, "GOLDEN", "not_enough_golden", player_id)
        player.golden -= GOLDEN_PATIENCE_COST
        player.order_deadline += PATIENCE_SECONDS
        return state, Outcome(True, "GOLDEN", "patience", player_id,
                              {"deadline": player.order_deadline})
    if effect == "restock":
        if player.golden < GOLDEN_RESTOCK_COST:
            return state, Outcome(False, "GOLDEN", "not_enough_golden", player_id)
        rng = _stream(state, f"restock:{player_id}:{player.dish_count}:{state.round_no}")
        player.golden -= GOLDEN_RESTOCK_COST
        new_tray = swap_one_letter(rng, player.order.tray, _kitchen(state).letter_profile)
        player.order = replace(player.order, tray=new_tray)
        player.tray_override = ""
        return state, Outcome(True, "GOLDEN", "restocked", player_id, {"tray": new_tray})
    if effect == "boost":
        if player.golden < GOLDEN_BOOST_COST:
            return state, Outcome(False, "GOLDEN", "not_enough_golden", player_id)
        player.golden -= GOLDEN_BOOST_COST
        player.boost_armed = True
        return state, Outcome(True, "GOLDEN", "boost_armed", player_id, {})
    return state, Outcome(False, "GOLDEN", "unknown_effect", player_id)


def ring_bell(state: MatchState, player_id: str, *,
              now: float | None = None) -> tuple[MatchState, Outcome]:
    """Chaos Kitchen: force a chaos event right now, aimed at the leader."""
    if state.mode != "CHAOS_KITCHEN":
        return state, Outcome(False, "BELL", "bells_only_ring_in_chaos", player_id)
    if not state.round_active:
        return state, Outcome(False, "BELL", "no_active_round", player_id)
    player = state.players.get(player_id)
    if player is None or player.golden < 1:
        return state, Outcome(False, "BELL", "need_one_golden_to_ring", player_id)
    leader_id = max(sorted(state.players), key=lambda pid: state.players[pid].score)
    player.golden -= 1
    rng = _stream(state, f"bell:{player_id}:{state.round_no}:{len(state.chaos_log)}")
    event = pick_chaos(rng, sorted(state.players), actor_id=player_id)
    if event.victim_id == player_id:
        event = ChaosEvent(event.event_type, player_id, leader_id, event.param)
    state = apply_chaos(state, event, now=now)
    return state, Outcome(True, "BELL", "chaos_unleashed", player_id, {"chaos": event.to_dict()})


def skip_order(state: MatchState, player_id: str, *,
               now: float | None = None) -> tuple[MatchState, Outcome]:
    """Pass the current ticket: combo resets, a fresh order arrives."""
    now = time.time() if now is None else now
    player = state.players.get(player_id)
    if player is None:
        return state, Outcome(False, "SKIP", "unknown_player", player_id)
    if not state.round_active or player.order is None:
        return state, Outcome(False, "SKIP", "no_active_order", player_id)
    kitchen = _kitchen(state)
    player.combo = 0
    rng = _stream(state, f"skip:{player_id}:{player.dish_count}:{state.round_no}")
    fresh = make_order(
        rng, load_dictionary(),
        order_id=f"{player.order.order_id}#skip{player.dish_count}",
        difficulty=_difficulty_for(player, player.order.difficulty, kitchen),
        profile=kitchen.letter_profile,
    )
    player.order = fresh
    player.order_started_at = now
    player.order_deadline = now + fresh.time_limit * kitchen.timer_mult
    player.streak_left = fresh.streak_needed
    return state, Outcome(True, "SKIP", "skipped", player_id,
                          {"next_order": fresh.to_dict()})


def round_complete(state: MatchState) -> bool:
    """A round closes when every chef served the quota (or the match is over)."""
    if not state.round_active:
        return False
    return all(p.round_dishes >= ROUND_DISHES for p in state.players.values())


def apply_intent(state: MatchState, player_id: str, intent: dict, *,
                 now: float | None = None) -> tuple[MatchState, Outcome]:
    """Dispatch one client intent. Unknown intents are rejected, never trusted."""
    action = str(intent.get("action", "")).upper()
    if action == "SUBMIT_DISH":
        return submit_dish(state, player_id, intent.get("word", ""),
                           use_spice=bool(intent.get("use_spice")), now=now)
    if action == "PREP":
        return submit_prep(state, player_id, intent.get("word", ""), now=now)
    if action == "GOLDEN":
        return use_golden(state, player_id, str(intent.get("effect", "")), now=now)
    if action == "RING_BELL":
        return ring_bell(state, player_id, now=now)
    if action == "SKIP":
        return skip_order(state, player_id, now=now)
    return state, Outcome(False, action or "UNKNOWN", "unknown_action", player_id)


def leaderboard(state: MatchState) -> list[dict]:
    rows = sorted(
        state.players.values(),
        key=lambda p: (-p.score, -p.dish_count, p.player_id),
    )
    return [{"position": i + 1, "player_id": p.player_id,
             "display_name": p.display_name, "score": p.score,
             "dishes": p.dish_count, "best_word": p.best_word}
            for i, p in enumerate(rows)]
